### PR TITLE
RK-13249 - Update rook and create an image

### PR DESCRIPTION
**Pull request by Urook**
Update rook and create an image

### CODE REVIEW

**Review by dan505512 — APPROVED** [review]

**Comment by dan505512** [comment]
Jira issue automation is not supported in this repository. Please contact your organization administrator for more information.

**Comment by Urook** [comment]
> Jira issue automation is not supported in this repository. Please contact your organization administrator for more information.

We can add it to the enforcer's relevant repo array

**Comment by dan505512** [comment]
[RK-13249](https://rookout.atlassian.net/browse/RK-13249)

**Comment by Urook** [comment]
@dan505512 Merged, but someone with permissions needs to push it as rookout/message-sender via the sonario account

**Pull request merged**
